<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getServices</value>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">TGlzdDxTZXJ2aWNlSW5mbz4gc2VydmljZXNJbmZvID0gU2VydmljZXNSZXRyaWV2ZXIuZ2V0KCku
Z2V0U2VydmljZXNJbmZvKCk7DQoNCklEYXRhW10gc2VydmljZXMgPSBuZXcgSURhdGFbc2Vydmlj
ZXNJbmZvLnNpemUoKV07DQppbnQgaSA9IDA7DQpmb3IgKFNlcnZpY2VJbmZvIHNpIDogc2Vydmlj
ZXNJbmZvKSB7DQogICAgSURhdGEgZGF0YSA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsNCiAgICBJ
RGF0YUN1cnNvciBkYyA9IGRhdGEuZ2V0Q3Vyc29yKCk7DQogICAgZGMuaW5zZXJ0QWZ0ZXIoImlk
eCIsIGkpOw0KICAgIGRjLmluc2VydEFmdGVyKCJkaXNwbGF5LW5hbWUiLCBzaS5nZXREaXNwbGF5
TmFtZSgpKTsNCiAgICBpZiAoc2kuZ2V0VmVyc2lvbigpICE9IG51bGwpIHsNCiAgICAgICAgU3Ry
aW5nIHZlcnNpb25JbmZvID0gIigiICsgc2kuZ2V0VmVyc2lvbigpICsgIikiOw0KICAgICAgICBk
Yy5pbnNlcnRBZnRlcigidmVyc2lvbiIsIHZlcnNpb25JbmZvKTsNCiAgICB9DQogICAgZGMuaW5z
ZXJ0QWZ0ZXIoInJlc3Qtc3RhY2stdXNlZCIsIHNpLmlzUmVzdFN0YWNrVXNlZCgpKTsNCiAgICBk
Yy5pbnNlcnRBZnRlcigic2VydmljZS10eXBlIiwgc2kuZ2V0VHlwZSgpLmdldERpc3BsYXlOYW1l
KCkpOw0KICAgIGRjLmluc2VydEFmdGVyKCJuYW1lIiwgc2kuZ2V0TmFtZSgpKTsNCiAgICBkYy5p
bnNlcnRBZnRlcigidXJsIiwgc2kuZ2V0VXJsKCkpOw0KICAgIGRjLmluc2VydEFmdGVyKCJkZXNj
cmlwdGlvbiIsIHNpLmdldERlc2NyaXB0aW9uKCkpOw0KICAgIGRjLmluc2VydEFmdGVyKCJjb25z
dW1lcnMiLCBzaS5nZXRDb25zdW1lcnMoKSk7DQogICAgZGMuaW5zZXJ0QWZ0ZXIoIm9wZXJhdGlv
bnMiLCBzaS5nZXRPcGVyYXRpb25zKCkpOw0KICAgIGlmIChzaS5nZXRXc2RsVXJsKCkgIT0gbnVs
bCkgew0KICAgICAgICBkYy5pbnNlcnRBZnRlcigid3NkbFVybCIsIHNpLmdldFdzZGxVcmwoKSAr
ICI/d3NkbCIpOw0KICAgICAgICAvLyBkYy5pbnNlcnRBZnRlcigid3NkbFhtbCIsIHNpLmdldFdz
ZGxYbWwoKSk7DQogICAgfQ0KICAgIHNlcnZpY2VzW2krK10gPSBkYXRhOw0KfQ0KDQpwaXBlbGlu
ZS5nZXRDdXJzb3IoKS5pbnNlcnRBZnRlcigic2VydmljZXMiLCBzZXJ2aWNlcyk7DQo=</value>
</Values>
