<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">logWarning</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKg0KKioqKiBOYW1lOiAgICAgICAgIGxvZ1dhcm5pbmcNCioqKiogUHVycG9zZTogICAgICBX
cml0ZSBhIGxvZzRqIGxvZyBtZXNzYWdlIG9mICJXQVJOSU5HIiBsZXZlbCBzZXZlcml0eQ0KKioq
KiAgICAgICAgICAgICAgIHNlcnZlciBsb2cgZmlsZS4NCg0KKioqLw0KDQovL1JldHJpZXZlIGlu
cHV0IHBhcmFtZXRlcnMgZnJvbSB0aGUgcGlwZWxpbmUNCi8vIHBpcGVsaW5lDQpJRGF0YUN1cnNv
ciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KCVN0cmluZwlsb2dnZXJO
YW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJsb2dnZXJOYW1lIiAp
Ow0KCVN0cmluZwlsb2dNZXNzYWdlID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJz
b3IsICJsb2dNZXNzYWdlIiApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQovLyBpbnB1
dA0KSURhdGEgaW5wdXQgPSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7DQoNCi8vIG91dHB1dA0KSURh
dGEgCW91dHB1dCA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsNCg0KDQoNCkxvZ2dlciBsb2dnZXIg
PSBvcmcuYXBhY2hlLmxvZ2dpbmcubG9nNGouTG9nTWFuYWdlci5nZXRMb2dnZXIobG9nZ2VyTmFt
ZSk7DQpsb2dnZXIud2FybigibG9jYWxob3N0IisiOiIrIjU1NTUiKyIgIiArbG9nTWVzc2FnZSk7
DQoNCg0KLy9hbHdheXMgZGVzdHJveSBjdXJzb3JzDQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7
</value>
</Values>
