<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">logDebug</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKg0KKioqKiBOYW1lOiAgICAgICAgIGxvZ0RlYnVnDQoqKioqIFB1cnBvc2U6ICAgICAgV3Jp
dGUgYSBsb2c0aiBsb2cgbWVzc2FnZSBvZiAiREVCVUciIGxldmVsIHNldmVyaXR5IA0KKioqKiAg
ICAgICAgICAgICAgIHNlcnZlciBsb2cgZmlsZS4NCiANCioqKi8NCg0KLy9SZXRyaWV2ZSBpbnB1
dCBwYXJhbWV0ZXJzIGZyb20gdGhlIHBpcGVsaW5lDQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3Ig
cGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCglTdHJpbmcJbG9nZ2VyTmFt
ZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAibG9nZ2VyTmFtZSIgKTsN
CglTdHJpbmcJbG9nTWVzc2FnZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29y
LCAibG9nTWVzc2FnZSIgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsJCQ0KDQpMb2dnZXIg
bG9nZ2VyID0gb3JnLmFwYWNoZS5sb2dnaW5nLmxvZzRqLkxvZ01hbmFnZXIuZ2V0TG9nZ2VyKGxv
Z2dlck5hbWUpOw0KbG9nZ2VyLmRlYnVnKCJsb2NhbCBIb3N0IisiOiIrIjU1NTUiKyIgIiArbG9n
TWVzc2FnZSk7DQoNCiANCi8vYWx3YXlzIGRlc3Ryb3kgY3Vyc29ycw0KcGlwZWxpbmVDdXJzb3Iu
ZGVzdHJveSgpOw0KCQ==</value>
</Values>
