<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getAliases</value>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9TeXN0ZW0ub3V0LnByaW50bG4oIioqKioqKkdldHRpbmcgYWxpYXNlcyAqKioqKioiKTsgDQpJ
RGF0YUN1cnNvciBjdXIgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCmJvb2xlYW4ga3NOYW1lID0g
Y3VyLmZpcnN0KCJrZXlTdG9yZSIpOw0KU3RyaW5nIGtleXN0b3JlID0gIiI7DQppZiAoa3NOYW1l
KSB7DQogICAgICBrZXlzdG9yZSA9IChTdHJpbmcpIGN1ci5nZXRWYWx1ZSgpOyAgICAgICANCn0N
CmVsc2Ugew0KICAvL2dldCB0aGUgYWxpYXNlcyBmb3IgdGhlIGN1cnJlbnQga2V5c3RvcmUgaGFu
ZGxlIGluIHRoZSBVSSANCiAgYm9vbGVhbiBrc0hhbmRsZVByZXNlbnQgPSBjdXIuZmlyc3QoInBn
LmtleXN0b3JlLmtleVN0b3JlSGFuZGxlIik7DQogIGlmIChrc0hhbmRsZVByZXNlbnQpIHsNCiAg
ICAgIGtleXN0b3JlID0gKFN0cmluZykgY3VyLmdldFZhbHVlKCk7DQogIH0NCg0KfQ0KDQovL1N5
c3RlbS5vdXQucHJpbnRsbigiR2V0dGluZyBhbGlhcyBmb3Iga2V5c3RvcmUgaGFuZGxlIDogKCIg
KyBrZXlzdG9yZSArICIpIiApOw0KDQppZiAoa2V5c3RvcmUhPW51bGwgJiYga2V5c3RvcmUubGVu
Z3RoKCk+MCkgew0KIHRyeSB7DQogICAgICAgICAgICBJU0tleVN0b3JlTWFuYWdlciBrc01nciA9
IElTS2V5U3RvcmVNYW5hZ2VyLmdldEluc3RhbmNlKCk7DQogICAgICAgICAgICBTdHJpbmdbXSBr
cyA9IGtzTWdyLmxpc3RLZXlBbGlhc2VzKGtleXN0b3JlKTsNCg0KCSAgICBJRGF0YVtdIG5hbWVz
ID0gbmV3IElEYXRhW2tzLmxlbmd0aF07DQoNCgkgICAgZm9yIChpbnQgaT0wOyBpPGtzLmxlbmd0
aDsgaSsrKSB7CQkNCgkJbmFtZXNbaV0gPSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7DQoJCW5hbWVz
W2ldLmdldEN1cnNvcigpLmluc2VydEFmdGVyKCJuYW1lIiwga3NbaV0pOw0KCSAgICB9DQoNCgkg
ICAgcGlwZWxpbmUuZ2V0Q3Vyc29yKCkuaW5zZXJ0QWZ0ZXIoQUxJQVNfTkFNRVMsIG5hbWVzKTsN
Cg0KICAgICAgICB9IGNhdGNoIChFeGNlcHRpb24gZSkgew0KICAgICAgICAJbG9nZ2VyLmVycm9y
KCIwMDEwLjA4NzEiLCBuZXcgT2JqZWN0W117IGUuZ2V0TWVzc2FnZSgpfSxlKTsNCiAgICAgICAg
fQ0KfQ0K</value>
</Values>
