<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getMenu</value>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCgkJDQoJ
SURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJ0ZXh0IiwgIk1lZGlhdG9yIiApOw0KCQkN
CglJbnZva2VTdGF0ZSBjdXJyU3RhdGUgPSBJbnZva2VTdGF0ZS5nZXRDdXJyZW50U3RhdGUoKTsN
CiAgICAgICAgaWYgKCBjdXJyU3RhdGUgIT0gbnVsbCApIHsNCiAgICAgICAgICAgIE5TU2Vydmlj
ZSBjdXJyU2VydmljZSA9IEludm9rZVN0YXRlLmdldEN1cnJlbnRTZXJ2aWNlKCk7DQogICAgICAg
ICAgICBpZiAoIGN1cnJTZXJ2aWNlICE9IG51bGwgKSB7DQogICAgICAgICAgICAgICAgTlNQYWNr
YWdlIGN1cnJQa2cgPSAoTlNQYWNrYWdlKSBjdXJyU2VydmljZS5nZXRQYWNrYWdlKCk7DQogICAg
ICAgICAgICAgICAgaWYgKCBjdXJyUGtnICE9IG51bGwgKSB7DQoJCSAgICAgICAgU3RyaW5nIHBr
Z05hbWUgPSBjdXJyUGtnLmdldE5hbWUoKTsNCgkJCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vy
c29yLCAidXJsIiwgIi8iK3BrZ05hbWUgKTsgIC8vaG9tZSBwYWdlDQoJICAgICAgICB9DQogICAg
ICAgICAgICB9DQogICAgICAgICB9DQoJSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgInRh
cmdldCIsICJyaWdodFNpZGUiKTsNCgkJDQoJcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0K</value>
</Values>
