<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">logInfo</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKg0KKioqKiBOYW1lOiAgICAgICAgIGxvZ0luZm8NCioqKiogUHVycG9zZTogICAgICBXcml0
ZSBhIGxvZzRqIGxvZyBtZXNzYWdlIG9mICJJTkZPIiBsZXZlbCBzZXZlcml0eQ0KKioqKiAgICAg
ICAgICAgICAgIHNlcnZlciBsb2cgZmlsZS4NCg0KKioqLw0KDQovL1JldHJpZXZlIGlucHV0IHBh
cmFtZXRlcnMgZnJvbSB0aGUgcGlwZWxpbmUNCi8vIHBpcGVsaW5lDQpJRGF0YUN1cnNvciBwaXBl
bGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KCVN0cmluZwlsb2dnZXJOYW1lID0g
SURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJsb2dnZXJOYW1lIiApOw0KCVN0
cmluZwlsb2dNZXNzYWdlID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJs
b2dNZXNzYWdlIiApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQoNCg0KdHJ5DQp7DQoN
CkxvZ2dlciBsb2dnZXIgPSBvcmcuYXBhY2hlLmxvZ2dpbmcubG9nNGouTG9nTWFuYWdlci5nZXRM
b2dnZXIobG9nZ2VyTmFtZSk7DQpsb2dnZXIuaW5mbygibG9jYWxob3N0IisiOiIrIjU1NTUiKyIg
IiArbG9nTWVzc2FnZSk7DQoNCg0KfWNhdGNoKCBFeGNlcHRpb24gZSl7IHRocm93IG5ldyBTZXJ2
aWNlRXhjZXB0aW9uKGUpO30NCi8vYWx3YXlzIGRlc3Ryb3kgY3Vyc29ycw0KcGlwZWxpbmVDdXJz
b3IuZGVzdHJveSgpOw0KCQ==</value>
</Values>
